version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /Users/cheney/Documents/docker/nginx/log:/var/log/nginx
      #   - /Users/cheney/Documents/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      #   - /Users/cheney/Documents/docker/nginx/conf.d:/etc/nginx/conf.d
      #   - /Users/cheney/Documents/docker/nginx/html:/usr/share/nginx/html
    links:
      - autodeploy
  
  nodeservice:
    build: ./nodeservice
    expose:
      - "3636"
  
  # x-grpc:
  #   build: ./x-grpc
  #   expose:
  #     - "50051"